### ISSUE TITLE
indirect parameterization

### ISSUE THREAD

**Issue by rhklite** [kalekundert/parametrize_from_file#14]
I was wondering if this package provides the ability to perform indirect parameterization?

**Comment by kalekundert** [comment]
Yes, indirect parametrization works.  Basically, the `indirect` argument to `@parametrize_from_file` is passed directly through to `@pytest.mark.parametrize`, so it works like normal.

Here's an example from one of my tests:
https://github.com/kalekundert/byoc/blob/dev/tests/test_cast.py#L35
