### ISSUE TITLE
Upper bound on `more_itertools` requirement

### ISSUE THREAD

**Issue by lkubb** [kalekundert/parametrize_from_file#24]
Before all else, thank you for creating and maintaining this library! I use it for testing an extension for Salt (https://github.com/saltstack/salt) and like the approach very much.

The issue I'm facing is that pip does not want to install both Salt and parametrize_from_file because of conflicting requirements regarding `more_itertools`. Salt currently pins it to `==9.1`, but parametrize_from_file requires `~=8.10`. Is there a known issue for versions >=9 or would it be possible to remove/adjust the upper bound?

Thanks again. :)

**Comment by kalekundert** [comment]
Good catch, the requirement should've been `more_itertools>=8.10`.  I just made a new release to PyPI with the correct requirement, so you should be able to install both packages now.

Thanks for the kind words, as well!
