### ISSUE TITLE
Installation other than with pip

### ISSUE THREAD

**Issue by adhawkins** [kalekundert/parametrize_from_file#5]
I'm trying to package this for Alpine, so that the build tests for my Emborg package can be run.

Any change of providing a setup.py so that it can be installed like any other Python package, without needing to go via PIP?

**Comment by kalekundert** [comment]
Let me know if I'm not understanding your constraints (I don't know anything about packaging for Alpine), but is there a reason you can't do:
```
$ git clone git@github.com:kalekundert/parametrize_from_file.git
$ cd parametrize_from_file
$ pip install .
```
My understanding is `pyproject.toml` currently accepted way to specify how a python project should be built/installed, and that using `setup.py` would be a step backwards.  See: [PEP 518](https://www.python.org/dev/peps/pep-0518/)

**Comment by adhawkins** [comment]
Apologies, since posting this I have been pointed into the correct way to do it for Alpine. Was about to come back and delete / close this issue.

Thanks for your input.
